import Head from 'next/head';
import dynamic from 'next/dynamic';
import LeftMenu from '../components/LeftMenu';
import Settings from '../components/Settings';
import { AssistantRoleProvider } from '../contexts/assistant';
import { OpenaiKeyProvider } from '../contexts/openaiKey';

const Chat = dynamic(() => import('../components/Chat'), { ssr: false });
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Easy Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <OpenaiKeyProvider>
          {/* Left Menu */}
          {/* <div style={{ width: '320px' }} className="max-h-screen bg-gray-800 flex flex-col justify-between">
            <LeftMenu />
            <Settings />
          </div> */}

          {/* Right Menu */}
          <div className="flex-1">
            <AssistantRoleProvider>
              <Chat />
            </AssistantRoleProvider>
          </div>
        </OpenaiKeyProvider>
      </main>
    </>
  )
}
